export const EIconName = {
  Plus: 'Plus',
  Launch: 'Launch',
  Advertising: 'Advertising',
  Insurange: 'Insurange',
  Stake: 'Stake',
  User: 'User',
  Incubator: 'Incubator',
  Home: 'Home',
  ArrowLeft: 'ArrowLeft',
  ArrowRight: 'ArrowRight',
  Twitter: 'Twitter',
  Facebook: 'Facebook',
  Instagram: 'Instagram',
  ThreeDots: 'ThreeDots',
  Telegram: 'Telegram',
  Youtube: 'Youtube',
  LinkedIn: 'LinkedIn',
  ArrowUp: 'ArrowUp',
  Menu: 'Menu',
  Dollar: 'Dollar',
  Flag: 'Flag',
  Figma: 'Figma',
  Clock: 'Clock',
  Code: 'Code',
  TrendingUp: 'TrendingUp',
  Layout: 'Layout',
  Zap: 'Zap',
  PhoneCall: 'PhoneCall',
  Mail: 'Mail',
  X: 'X',
  Copy: 'Copy',
  HouseGlass: 'HouseGlass',
  VeritfyCompleted: 'VeritfyCompleted',
  CircleCheck: 'CircleCheck',
  Heart: 'Heart',
};

export const EIconColor = {
  BLACK: '#000',
  WHITE: '#fff',
  NEUTRAL_7: '#82898C',
  PRIMARY_LC_6: '#7CC9E6',
  PRIMARY_LC_8: '#DFF3F9',
  DANGER_2: '#E1594C',
  SUCCESS_2: '#9BC937',
};
